import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./global/js/slick/slick.css";
import "./global/styles/reset.css";
import "./global/styles/style.css";
import "./global/styles/style.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script src="src/slick/slick.min.js"></Script>
        <Script src="js/slick-initializer.js"></Script>
        <Script src="js/base-Script.js"></Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
